import Head from 'next/head'
import styles from '../styles/new.module.css'

const Main = ()=>{
    return(
        <div className='ill'>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1>
            ill
        </h1>
       
        </div> 
    )
}
export default Main